version: "3.8"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb_data:/data

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data

  server:
    build: ./server
    container_name: server
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
      - redis
    environment:
      - DB_LOCAL=mongodb://mongodb:27017/mydatabase
      - REDIS_URL=redis://redis:6379
      - PORT=8000
    volumes:
      - ./server:/server

  client:
    build: ./vite client
    container_name: client
    ports:
      - "5173:5173"
    depends_on:
      - server
    environment:
      - VITE_BASE_URL=http://localhost:8000/
    volumes:
      - ./vite client:/client
